### ISSUE TITLE
settings.json

### ISSUE THREAD

**Issue by itiremiroglu** [thecodercoder/fem-easybank#9]
Dear @thecodercoder you wrote to description of the video, "you can write that snippet
"liveSassCompile.settings.formats": [
    {
      "format": "expanded",
      "extensionName": ".css",
      "savePath": "/dist",
      "savePathSegmentKeys": null,
      "savePathReplaceSegmentsWith": null
    }
  ],
  but I get Property savePathSegmentKeys is not allowed.
  Property savePathReplaceSegmentsWith is not allowed.
  What can I do for dismiss these errors?
  thanks for the responding to this issue from now on.

**Comment by thecodercoder** [comment]
The extension may have changed their settings in the meantime. What you can do instead of copying and pasting the snippet is, in your settings.json file, start typing `"liveSassCompile"` (using double quotes) and the auto-complete should pop up different options. Select the "liveSassCompile.settings.formats" and it will auto populate the available settings. Hope this helps!

**Comment by itiremiroglu** [comment]
I'm not sure but when I start to type as you said, it populated
```
{
  "liveSassCompile.settings.formats": [
    {
      "format": "expanded",
      "extensionName": ".css",
      "savePath": null
    }
  ]
}
```
Should I add different options or not?

**Comment by thecodercoder** [comment]
No, it will automatically add all the available settings, you won't be able to add any more settings. This is why you were getting the error in the first place-- the savePathSegmentKeys and savePathReplaceSegmentsWith options are no longer used in the extension, so they needed to be removed.
